config/routes.rb
Rails.application.routes.draw do
  root "top#patient_login"

  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"

  resource :patients, only: [:new, :create]

  get "/doctor_login" => "top#doctor_login"
  get "/admin_login" => "top#admin_login"
  get "/patient_login" => "top#patient_login"
  get "/reception_login" => "top#reception_login"
  
  # 患者のルーティング
  namespace :patient do
    root "patients#index"
    resources :patients, except: [:new, :create]
    resources :doctors, only: [:index, :show] do
      resources :slots, only: [:index, :show] do
        resources :appointments do
          get "confirm",on: :member
        end
      end
    end
    resources :appointments, only: [:create]
    resources :departments, only: [:index, :show] do
      resources :slots, only: [:index, :show]
    end

    resource :session, only: [:create, :destroy]
  end

  # 医者のルーティング
  namespace :doctor  do
    root "doctors#index"
    resources :patients, only: [:index, :show] do
      get "search", on: :collection
    end
    resources :doctors, only: [:index, :show] do
      resources :appointments, only: [:index, :destroy]
    end
    resource :session, only: [:create, :destroy]
    resources :checks, only: [:index, :show, :destroy]
  end

  # 管理者のルーティング
  namespace :admin do
    root "top#index"
    get "/getdoctor" => "top#doctor"
    get "/doctor(/:doctor_id)/slots" => "top#slots"
    resources :patients, only: [:index, :show, :destroy] do
      get "search", on: :collection
    end
    resources :doctors do
      get "search", on: :collection
    end
    resources :appointments, only: [:destroy]
    resources :slots, only: [:index, :new, :show, :create, :destroy]
    resources :checks, only: [:index, :show]
    resource :session, only: [:create, :destroy]
  end

  # 受付のルーティング
  namespace :reception do
    root "appointments#index"
    resources :appointments, only: [:index, :show] do
      resources :checks  do
        get "confirm",on: :member
      end
    end
    resources :checks, only: [:index, :create]
    resource :session, only: [:create, :destroy]
  end
end

app/views/shared/_admin_menubar.html.erb
<ul>
        <%= menu_link_to "TOP", :admin_root %>
        <%= menu_link_to "医者情報管理", :admin_doctors %>
        <%= menu_link_to "新規医者登録", :new_admin_doctor %>
        <%= menu_link_to "患者情報管理", :admin_patients %>
        <%= menu_link_to "予約情報確認", :admin_getdoctor %>
</ul>

app/views/shared/_appointment.html.erb
<% if @appointments.present? %>
予約一覧
<table class="list">
  <thead>
    <tr>
      <th>日時</th>
      <th>医者名</th>
      <th>診察科</th>
      <th>操作</th>
    </tr>
  </thead>
  <% @appointments.each do |appointment| %>
    <tr>
      <td><%=  appointment.time.strftime("%m/%d %H:%M") %></td>
      <td><%=  appointment.slot.doctor.username %></td>
      <td><%=  appointment.slot.doctor.department.name %></td>
      <td>
      <% if current_patient %>
      <%= link_to "キャンセル", patient_doctor_slot_appointment_path(appointment.slot.doctor, appointment.slot, appointment), method: :delete,
              data: { confirm: "予約をキャンセルしますか?" } %>
              </td>
      <% end %>
      <% if current_doctor %>
      <%= link_to "予約削除", doctor_doctor_appointment_path(doctor_id: current_doctor.id, id: appointment.id), method: :delete,
        data: { confirm: "予約を削除しますか?" } %>
              </td>
      <% end %>
      <% if current_administrator %>
      <%= link_to "予約削除", admin_appointment_path(id: appointment.id), method: :delete,
              data: { confirm: "予約を削除しますか?" } %>
              </td>
      <% end %>

    </tr>
  <% end %>
</table>
<else>
現在予約はありません
<% end %>

app/views/shared/_checks.html.erb
<% if @checks.present? %>
<table class="list">
  <thead>
    <tr>
      <th>受付番号</th>
      <th>日時</th>
      <th>医者名</th>
      <th>患者名</th>
      <th>診察科</th>
    </tr>
  </thead>
  <% @checks.each do |check| %>
    <tr>
      <td><%=  check.id %></td>
      <td><%=  check.appointment.time.strftime("%m/%d %H:%M") %></td>
      <td><%=  check.appointment.slot.doctor.username %></td>
      <td><%=  check.appointment.patient.username %></td>
      <td><%=  check.appointment.slot.doctor.department.name %></td>
    </tr>
  <% end %>
</table>
<% else %>
現在順番待ちはありません
<% end %>

app/views/shared/_doctor_checks.html.erb
<% if @checks.present? %>
<table class="list">
  <thead>
    <tr>
      <th>日時</th>
      <th>受付番号</th>
      <th>患者名</th>
      <th>患者番号</th>
      <th>診察終了</th>
    </tr>
  </thead>
  <% @checks.each do |check| %>
    <tr>
      <td><%=  check.appointment.time.strftime("%m/%d %H:%M") %></td>
      <td><%=  check.id %></td>
      <td><%=  check.appointment.patient.username %></td>
      <td><%=  check.appointment.patient.id %></td>
      <td><%= link_to "◯", doctor_check_path(check), method: :delete,
      data: { confirm: "診察を終了しますか?" } %>
      </td>
    </tr>
  <% end %>
</table>
<% else %>
現在順番待ちはありません
<% end %>

app/views/shared/_doctor_menubar.html.erb
<ul>
        <%= menu_link_to "TOP", :doctor_root %>
        <%= menu_link_to "患者一覧", :doctor_patients %>
        <%= menu_link_to "診察チェック", :doctor_checks %>
</ul>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
  <div id="errors">
    <h3>エラーがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
Copyright (C) <%= link_to "R", "https://docs.google.com/presentation/d/1qIxZ3s1tq4XFNDYW60C5ws8-2eym9CRvUz0MSlx66OA/edit?pli=1#slide=id.g28e909100fd_6_7" %>
2024

app/views/shared/_header.html.erb
<% @page_title = "中川クリニック" %>
<h1><%= @page_title %></h1>

<% if current_patient %>
  <ul class="account-menu">
  <%= menu_link_to current_patient.username + "さん", edit_patient_patient_path(current_patient.id) %>
    <%= menu_link_to "ログアウト", :patient_session,
      method: :delete, data: { confirm: "ログアウトしますか？" } %>
  </ul>
<% end %>

<% if current_doctor %>
  <ul class="account-menu">
  <%= current_doctor.username + "さん"%>
    <%= menu_link_to "ログアウト", :doctor_session,
      method: :delete, data: { confirm: "ログアウトしますか？" } %>
  </ul>
<% end %>

<% if current_administrator %>
  <ul class="account-menu">
  <%= current_administrator.username + "さん" %>
    <%= menu_link_to "ログアウト", :admin_session,
      method: :delete, data: { confirm: "ログアウトしますか？" } %>
  </ul>
<% end %>

<% if current_reception%>
  <ul class="account-menu">
  <%= current_reception.username + "さん" %>
    <%= menu_link_to "ログアウト", :reception_session,
      method: :delete, data: { confirm: "ログアウトしますか？" } %>
  </ul>
<% end %>

<%=render "shared/menubar"%>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>
<% if flash.alert %><p class="alert"><%= flash.alert %></p><% end %>
<%= form_tag :session, id: "login_form" do %>
    <div>
        <label>ユーザー名：</label>
        <input type="text" name="name">
    </div>
    <div>
        <label>パスワード：</label>
        <input type="password" name="password">
    </div>
    <div>
        <input type="submit" value="ログイン">
    </div>

 
    <ul class="account-menu">
    <%= menu_link_to "会員登録はこちら", :new_account %>
    </ul>
<% end %>

app/views/shared/_menubar.html.erb
<nav class="menubar">
  <ul>
  <%= menu_link_to "TOP", :root unless current_patient || current_administrator || current_doctor || current_reception%>
  <%= menu_link_to "初めて受診される方", :new_patients unless current_patient || current_administrator || current_doctor || current_reception%>
    <% if current_patient %>
        <%=render "shared/patient_menubar"%>
    <% end %>
    <% if current_doctor %>
        <%=render "shared/doctor_menubar"%>
    <% end %>
    <% if current_reception %>
        <%=render "shared/reception_menubar"%>
    <% end %>
    <% if current_administrator %>
        <%=render "shared/admin_menubar"%>
    <% end %>

  </ul>
</nav>

app/views/shared/_patient_menubar.html.erb
  <ul>
      <%= menu_link_to "TOP", :patient_root %>
      <%= menu_link_to "web予約", :patient_departments %>
      <%= menu_link_to "マイページ", patient_patient_path(current_patient.id) %>
  </ul>

app/views/shared/_reception_appointment.html.erb
<% if @appointments.present? %>
<table class="list">
  <thead>
    <tr>
      <th>日時</th>
      <th>医者名</th>
      <th>患者名</th>
      <th>診察科</th>
      <th>操作</th>
    </tr>
  </thead>
  <% @appointments.each do |appointment| %>
    <tr>
      <td><%=  appointment.time.strftime("%m/%d %H:%M") %></td>
      <td><%=  appointment.slot.doctor.username %></td>
      <td><%=  appointment.patient.username %></td>
      <td><%=  appointment.slot.doctor.department.name %></td>
      <td>
      <%= link_to "受付済みにする", confirm_reception_appointment_check_path(appointment_id: appointment.id, id: Check.count+1) %>
    </tr>
  <% end %>
</table>
<% else %>
現在の予約はありません
<% end %>

app/views/shared/_reception_menubar.html.erb
<ul>
      <%= menu_link_to "TOP", :reception_root %>
      <%= menu_link_to "診察待ちの方", :reception_checks %>
</ul>